// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: carts.sql

package db

import (
	"context"
)

const deleteCartItem = `-- name: DeleteCartItem :exec
DELETE FROM cart_items
WHERE cart_id = $1 AND product_id = $2
`

type DeleteCartItemParams struct {
	CartID    int64
	ProductID int64
}

func (q *Queries) DeleteCartItem(ctx context.Context, arg DeleteCartItemParams) error {
	_, err := q.db.Exec(ctx, deleteCartItem, arg.CartID, arg.ProductID)
	return err
}

const ensureCart = `-- name: EnsureCart :one
INSERT INTO carts (user_id)
VALUES ($1)
ON CONFLICT (user_id) DO UPDATE
    SET user_id = EXCLUDED.user_id
RETURNING id, user_id
`

func (q *Queries) EnsureCart(ctx context.Context, userID int64) (Cart, error) {
	row := q.db.QueryRow(ctx, ensureCart, userID)
	var i Cart
	err := row.Scan(&i.ID, &i.UserID)
	return i, err
}

const getCartByUser = `-- name: GetCartByUser :one
SELECT id, user_id
FROM carts
WHERE user_id = $1
`

func (q *Queries) GetCartByUser(ctx context.Context, userID int64) (Cart, error) {
	row := q.db.QueryRow(ctx, getCartByUser, userID)
	var i Cart
	err := row.Scan(&i.ID, &i.UserID)
	return i, err
}

const listCartItems = `-- name: ListCartItems :many
SELECT ci.product_id, p.name, p.price_cents, ci.quantity
FROM cart_items ci
         JOIN products p ON p.id = ci.product_id
WHERE ci.cart_id = $1
ORDER BY ci.product_id
`

type ListCartItemsRow struct {
	ProductID  int64
	Name       string
	PriceCents int64
	Quantity   int64
}

func (q *Queries) ListCartItems(ctx context.Context, cartID int64) ([]ListCartItemsRow, error) {
	rows, err := q.db.Query(ctx, listCartItems, cartID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCartItemsRow
	for rows.Next() {
		var i ListCartItemsRow
		if err := rows.Scan(
			&i.ProductID,
			&i.Name,
			&i.PriceCents,
			&i.Quantity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertCartItem = `-- name: UpsertCartItem :exec
INSERT INTO cart_items (cart_id, product_id, quantity)
VALUES ($1, $2, $3)
ON CONFLICT (cart_id, product_id) DO UPDATE
    SET quantity = EXCLUDED.quantity
`

type UpsertCartItemParams struct {
	CartID    int64
	ProductID int64
	Quantity  int64
}

func (q *Queries) UpsertCartItem(ctx context.Context, arg UpsertCartItemParams) error {
	_, err := q.db.Exec(ctx, upsertCartItem, arg.CartID, arg.ProductID, arg.Quantity)
	return err
}
