// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Cart struct {
	ID     int64
	UserID int64
}

type CartItem struct {
	CartID    int64
	ProductID int64
	Quantity  int64
}

type Order struct {
	ID         int64
	UserID     int64
	TotalCents int64
	CreatedAt  pgtype.Timestamptz
}

type OrderItem struct {
	ID          int64
	OrderID     int64
	ProductID   int64
	ProductName string
	PriceCents  int64
	Quantity    int64
}

type Product struct {
	ID          int64
	SellerID    int64
	Name        string
	Description string
	PriceCents  int64
	Stock       int64
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
}

type User struct {
	ID           int64
	Email        string
	PasswordHash string
	Name         string
	CreatedAt    pgtype.Timestamp
}
