// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: orders.sql

package db

import (
	"context"
)

const clearCart = `-- name: ClearCart :exec
DELETE FROM cart_items
WHERE cart_id = $1
`

func (q *Queries) ClearCart(ctx context.Context, cartID int64) error {
	_, err := q.db.Exec(ctx, clearCart, cartID)
	return err
}

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (user_id, total_cents)
VALUES ($1, $2)
RETURNING id, user_id, total_cents, created_at
`

type CreateOrderParams struct {
	UserID     int64
	TotalCents int64
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder, arg.UserID, arg.TotalCents)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TotalCents,
		&i.CreatedAt,
	)
	return i, err
}

const createOrderItem = `-- name: CreateOrderItem :exec
INSERT INTO order_items (order_id, product_id, product_name, price_cents, quantity)
VALUES ($1, $2, $3, $4, $5)
`

type CreateOrderItemParams struct {
	OrderID     int64
	ProductID   int64
	ProductName string
	PriceCents  int64
	Quantity    int64
}

func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) error {
	_, err := q.db.Exec(ctx, createOrderItem,
		arg.OrderID,
		arg.ProductID,
		arg.ProductName,
		arg.PriceCents,
		arg.Quantity,
	)
	return err
}

const decreaseStock = `-- name: DecreaseStock :execrows
UPDATE products
SET stock = stock - $1,
    updated_at = now()
WHERE id = $2 AND stock >= $1
`

type DecreaseStockParams struct {
	Quantity int64
	ID       int64
}

func (q *Queries) DecreaseStock(ctx context.Context, arg DecreaseStockParams) (int64, error) {
	result, err := q.db.Exec(ctx, decreaseStock, arg.Quantity, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getOrder = `-- name: GetOrder :one
SELECT id, user_id, total_cents, created_at
FROM orders
WHERE id = $1 AND user_id = $2
`

type GetOrderParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) GetOrder(ctx context.Context, arg GetOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, getOrder, arg.ID, arg.UserID)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TotalCents,
		&i.CreatedAt,
	)
	return i, err
}

const getProductForUpdate = `-- name: GetProductForUpdate :one
SELECT id, name, price_cents, stock
FROM products
WHERE id = $1
    FOR UPDATE
`

type GetProductForUpdateRow struct {
	ID         int64
	Name       string
	PriceCents int64
	Stock      int64
}

func (q *Queries) GetProductForUpdate(ctx context.Context, id int64) (GetProductForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getProductForUpdate, id)
	var i GetProductForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PriceCents,
		&i.Stock,
	)
	return i, err
}

const listOrderItems = `-- name: ListOrderItems :many
SELECT product_id, product_name, price_cents, quantity
FROM order_items
WHERE order_id = $1
ORDER BY id
`

type ListOrderItemsRow struct {
	ProductID   int64
	ProductName string
	PriceCents  int64
	Quantity    int64
}

func (q *Queries) ListOrderItems(ctx context.Context, orderID int64) ([]ListOrderItemsRow, error) {
	rows, err := q.db.Query(ctx, listOrderItems, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOrderItemsRow
	for rows.Next() {
		var i ListOrderItemsRow
		if err := rows.Scan(
			&i.ProductID,
			&i.ProductName,
			&i.PriceCents,
			&i.Quantity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdersByUser = `-- name: ListOrdersByUser :many
SELECT id, user_id, total_cents, created_at
FROM orders
WHERE user_id = $1
ORDER BY id DESC
`

func (q *Queries) ListOrdersByUser(ctx context.Context, userID int64) ([]Order, error) {
	rows, err := q.db.Query(ctx, listOrdersByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TotalCents,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
